---
- name: Add VLANs to devices(s)
  hosts: leaf1
  become: yes
  tasks:
    - name: Configure VLAN 10
      arista.eos.eos_vlans:
        config: 
          - vlan_id: 10
            name: DMZ
            state: active
        state: merged

