---
- name: Add VLANs to devices(s) via loop
  hosts: leafs
  become: yes
  tasks:
    - name: Configure VLANs on the leafs via a loop
      arista.eos.eos_vlans:
        config: 
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
            state: active
        state: merged
      loop: "{{ global_vlans }}"