---
- name: playbook for applying configlets to devices
  hosts: cvp1
  gather_facts: false
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: apply configlets to devices
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_MLAG }}"
        state: present
        apply_mode: loose
        