---
- name: Create container topology
  hosts: cvp1
  gather_facts: false
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: set container topology
      arista.cvp.cv_container_v3:
        topology: "{{ CVP_CONTAINERS}}"