---
- name: Reset devices configuration to default
  hosts: cvp1
  gather_facts: false
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: Apply default configlets to the devices
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_DEFAULT }}"
        apply_mode: strict
      register: CVP_CHANGE
    - name: Run tasks from previous tasks
      arista.cvp.cv_task_v3:
        tasks: "{{ CVP_CHANGE.taskIds }}"