---
- name: Run all pending tasks
  hosts: cvp1
  gather_facts: false
  tasks:
    - name: Grab and register gather_facts
      arista.cvp.cv_facts_v3:
        facts:
          - tasks
        regexp_filter: 'Pending'
      register: CVP_FACTS
    - name: Run all pending tasks
      arista.cvp.cv_task_v3:
        tasks: "{{ CVP_FACTS.data.cvp_tasks | list }}"