---
- name: Playbook for uploading configlet to cloudvision
  hosts: cvp1
  gather_facts: false
  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: upload configlets
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"
        state: present