---
- name: Deploy fabric to CVP
  hosts: cvp1
  tasks:
    - name: Provision CVP with AVD configuration
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'FABRIC'
        configlets_prefix: 'AVD-KSL3LS'
        state: present
        execute_tasks: false
        cv_collection: v3
